#!/usr/bin/env python3
"""
Description: Creates device specific secrets
Use: Once per device
"""
import os
import json
from argparse import ArgumentParser



def main(region_names, user_names, user_secrets, region_secrets, device_dir):
    file_name = "secrets.h"

    if (os.path.exists(device_dir + file_name)):
        os.remove(device_dir + file_name)
    # create device secrets file
    try:
        device_secrets = open(os.path.join(device_dir, file_name), "w")
    except Exception as e:
        print("Unable to open secrets file: {e}".format(e=e))
        return

    # check for valid region names
    try:
        rids = [str(region_secrets[r]) for r in region_names]
    except Exception as e:
        print("Unable to create secrets file: {e} "
              "Please ensure all regions entered are in the list: {user_secrets}".format(e=e, user_secrets=user_secrets.keys()))
        return

    # check for valid user names
    try:
        uids = [str(user_secrets[u]['id']) for u in usernames]
    except Exception as e:
        print("Unable to create secrets file: {e} "
              "Please ensure all regions entered are in the list: {user_secrets}".format(e=e, user_secrets=user_secrets.keys()))
        return

    # write secrets
    device_secrets.write(f'''
#ifndef SECRETS_H
#define SECRETS_H

#define NUM_REGIONS {len(region_secrets)}
const char *REGION_NAMES[] = {{ {", ".join(['"' + r + '"' for r in region_secrets])} }};
const u8 REGION_IDS[] = {{ {", ".join([str(r) for r in region_secrets.values()])} }};

#define NUM_PROVISIONED_REGIONS {len(region_names)}
const u8 PROVISIONED_RIDS[] = {{ {", ".join(rids)} }};

#define NUM_USERS {len(user_secrets)}
const char *USERNAMES[] = {{ {", ".join(['"' + u + '"' for u in user_secrets])} }};
const u8 USER_IDS[] = {{ {", ".join([str(user_secrets[u]['id']) for u in user_names])} }};

#define NUM_PROVISIONED_USERS {len(user_names)}
const u8 PROVISIONED_UIDS[] = {{ {", ".join(uids)} }};
const char *PROVISIONED_PINS[] = {{ {", ".join(['"' + user_secrets[u]['pin'] + '"' for u in user_names])} }};

#endif // SECRETS_H
''')
    runtime_src_path = "../../../mb/BYOT_runtime/src/"

def get_args():
    """gets arguments from command line"""
    parser = ArgumentParser(description='main interface to provision system')
    parser.add_argument('--region-list', nargs='+', help='Regions the player is provisioned for.', required=True)
    parser.add_argument('--region-secrets-path', help='Path to region secrets file.', required=True)
    parser.add_argument('--user-list', help='List of users seperated by a space to provision the device for.',
                        nargs='+', required=True)
    parser.add_argument('--user-secrets-path', help='Path to user secrets file generated in createUsers.py',
                        required=True)
    #parser.add_argument('--device-dir', help='Path to output any required information for the device.',
                        #required=True)
    args = parser.parse_args()
    return args.region_list, args.region_secrets_path, args.user_list, args.user_secrets_path


if __name__ == '__main__':
    device_dir = "../../mb/Secure_DRM/src/"
    region_names, region_secrets, usernames, user_secrets = get_args()
    print("generating device specific secrets")
    user_secrets = json.load(open(os.path.abspath(user_secrets)))
    region_secrets = json.load(open(os.path.abspath(region_secrets)))
    main(region_names, usernames, user_secrets, region_secrets, device_dir)