#pragma line 1 "blake2s.c" ::: -10
#pragma line 1 "blake2s.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 296 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 2
#pragma line 7 "<command line>" 2 ::: 118
#pragma line 1 "<built-in>" 2 ::: 119
#pragma line 1 "blake2s.c" 2 ::: 120
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 121
#pragma line 33 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 3 ::: 122
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 123
#pragma line 26 "/usr/include/stdint.h" 3 4 ::: 124
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 125
#pragma line 33 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 126
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 127
#pragma line 439 "/usr/include/features.h" 3 4 ::: 128
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 129
#pragma line 440 "/usr/include/features.h" 2 3 4 ::: 130
#pragma line 461 "/usr/include/features.h" 3 4 ::: 131
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 132
#pragma line 452 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 133
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 134
#pragma line 453 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 135
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/long-double.h" 1 3 4 ::: 136
#pragma line 454 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 137
#pragma line 462 "/usr/include/features.h" 2 3 4 ::: 138
#pragma line 485 "/usr/include/features.h" 3 4 ::: 139
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 140
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 141
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 142
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 143
#pragma line 486 "/usr/include/features.h" 2 3 4 ::: 144
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 2 3 4 ::: 145
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 146
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 147
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 148
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 149
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 150
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/timesize.h" 1 3 4 ::: 151
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 152
#pragma line 141 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 198
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 199
#pragma line 142 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 200
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time64.h" 1 3 4 ::: 201
#pragma line 143 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 202
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 275
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 276
#pragma line 29 "/usr/include/stdint.h" 2 3 4 ::: 277
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 278
#pragma line 30 "/usr/include/stdint.h" 2 3 4 ::: 279
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h" 1 3 4 ::: 284
#pragma line 24 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h" 3 4 ::: 285
#pragma line 35 "/usr/include/stdint.h" 2 3 4 ::: 290
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h" 1 3 4 ::: 293
#pragma line 24 "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h" 3 4 ::: 294
#pragma line 38 "/usr/include/stdint.h" 2 3 4 ::: 299
#pragma line 71 "/usr/include/stdint.h" 3 4 ::: 325
#pragma line 87 "/usr/include/stdint.h" 3 4 ::: 331
#pragma line 101 "/usr/include/stdint.h" 3 4 ::: 336
#pragma line 34 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 339
#pragma line 2 "blake2s.c" 2 ::: 340
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 341
#pragma line 26 "/usr/include/string.h" 3 4 ::: 342
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 343
#pragma line 27 "/usr/include/string.h" 2 3 4 ::: 344
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 351
#pragma line 31 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 352
#pragma line 34 "/usr/include/string.h" 2 3 4 ::: 363
#pragma line 43 "/usr/include/string.h" 3 4 ::: 364
#pragma line 91 "/usr/include/string.h" 3 4 ::: 388
#pragma line 122 "/usr/include/string.h" 3 4 ::: 391
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 1 3 4 ::: 424
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 3 4 ::: 425
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h" 1 3 4 ::: 426
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h" 3 4 ::: 427
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 2 3 4 ::: 443
#pragma line 154 "/usr/include/string.h" 2 3 4 ::: 446
#pragma line 226 "/usr/include/string.h" 3 4 ::: 470
#pragma line 253 "/usr/include/string.h" 3 4 ::: 473
#pragma line 273 "/usr/include/string.h" 3 4 ::: 476
#pragma line 303 "/usr/include/string.h" 3 4 ::: 483
#pragma line 330 "/usr/include/string.h" 3 4 ::: 486
#pragma line 385 "/usr/include/string.h" 3 4 ::: 506
#pragma line 410 "/usr/include/string.h" 3 4 ::: 520
#pragma line 428 "/usr/include/string.h" 3 4 ::: 522
#pragma line 1 "/usr/include/strings.h" 1 3 4 ::: 528
#pragma line 23 "/usr/include/strings.h" 3 4 ::: 529
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 530
#pragma line 24 "/usr/include/strings.h" 2 3 4 ::: 531
#pragma line 34 "/usr/include/strings.h" 3 4 ::: 532
#pragma line 68 "/usr/include/strings.h" 3 4 ::: 542
#pragma line 96 "/usr/include/strings.h" 3 4 ::: 545
#pragma line 433 "/usr/include/string.h" 2 3 4 ::: 586
#pragma line 3 "blake2s.c" 2 ::: 617
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 618
#pragma line 27 "/usr/include/stdio.h" 3 4 ::: 619
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 620
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 621
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 627
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 628
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 631
#pragma line 30 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 632
#pragma line 48 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 634
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 636
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 1 3 4 ::: 639
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h" 1 3 4 ::: 644
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h" 3 4 ::: 645
#pragma line 6 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 2 3 4 ::: 655
#pragma line 40 "/usr/include/stdio.h" 2 3 4 ::: 665
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h" 1 3 4 ::: 666
#pragma line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h" 3 4 ::: 667
#pragma line 41 "/usr/include/stdio.h" 2 3 4 ::: 673
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h" 1 3 4 ::: 674
#pragma line 42 "/usr/include/stdio.h" 2 3 4 ::: 680
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h" 1 3 4 ::: 681
#pragma line 43 "/usr/include/stdio.h" 2 3 4 ::: 689
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 1 3 4 ::: 690
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 3 4 ::: 691
#pragma line 44 "/usr/include/stdio.h" 2 3 4 ::: 757
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 767
#pragma line 77 "/usr/include/stdio.h" 3 4 ::: 769
#pragma line 133 "/usr/include/stdio.h" 3 4 ::: 778
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 779
#pragma line 134 "/usr/include/stdio.h" 2 3 4 ::: 780
#pragma line 173 "/usr/include/stdio.h" 3 4 ::: 801
#pragma line 187 "/usr/include/stdio.h" 3 4 ::: 803
#pragma line 204 "/usr/include/stdio.h" 3 4 ::: 810
#pragma line 227 "/usr/include/stdio.h" 3 4 ::: 826
#pragma line 246 "/usr/include/stdio.h" 3 4 ::: 828
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 838
#pragma line 292 "/usr/include/stdio.h" 3 4 ::: 840
#pragma line 379 "/usr/include/stdio.h" 3 4 ::: 910
#pragma line 432 "/usr/include/stdio.h" 3 4 ::: 945
#pragma line 485 "/usr/include/stdio.h" 3 4 ::: 978
#pragma line 510 "/usr/include/stdio.h" 3 4 ::: 995
#pragma line 521 "/usr/include/stdio.h" 3 4 ::: 997
#pragma line 537 "/usr/include/stdio.h" 3 4 ::: 1006
#pragma line 577 "/usr/include/stdio.h" 3 4 ::: 1036
#pragma line 603 "/usr/include/stdio.h" 3 4 ::: 1038
#pragma line 673 "/usr/include/stdio.h" 3 4 ::: 1090
#pragma line 707 "/usr/include/stdio.h" 3 4 ::: 1113
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1120
#pragma line 757 "/usr/include/stdio.h" 3 4 ::: 1127
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1153
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 3 4 ::: 1154
#pragma line 782 "/usr/include/stdio.h" 2 3 4 ::: 1157
#pragma line 800 "/usr/include/stdio.h" 3 4 ::: 1168
#pragma line 840 "/usr/include/stdio.h" 3 4 ::: 1182
#pragma line 858 "/usr/include/stdio.h" 3 4 ::: 1191
#pragma line 4 "blake2s.c" 2 ::: 1194
#pragma line 1 "./blake2s.h" 1 ::: 1196
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1199
#pragma line 4 "./blake2s.h" 2 ::: 1200
#pragma line 22 "./blake2s.h" ::: 1201
#pragma line 6 "blake2s.c" 2 ::: 1216
#pragma line 174 "blake2s.c" ::: 1374
